# Shared settings (across all three methods)
seed: 123
predictor: model
distance_threshold: 7
prediction_threshold: 0.6
penalty_term: 1.1
distance_function: "weighted"   # alternative: "l1", "weighted"
method: "knn"             # alternative: "knn", "epsilon", "kde"
directed: True

kde: 
  density_threshold: 1e-5 

knn:
  n_neighbours: 5

epsilon:
